-- init.sql
CREATE TABLE IF NOT EXISTS USER (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL
);
